version: '3'

networks:
  cboard-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - "/data/db:/data/db"
    networks:
      - cboard-network

  cboard-api:
    image: cboard/cboard-api
    restart: on-failure
    ports:
      - "5000:80"
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongodb/cboard-api
      - NODE_ENV=production
      - SENDGRID_API_KEY
      - JWT_SECRET  
  
    networks:
      - cboard-network
    depends_on:
      - mongodb
  
  cboard:
    image: cboard/cboard
    restart: on-failure
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    networks:
      - cboard-network
    depends_on:
      - cboard-api
  
  letsencrypt:
    image: cboard/letsencrypt
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt
volumes:
  letsencrypt_certs: ~
  letsencrypt_www: ~
