version: 2

jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t cboard/cboard-bootstrap:$TAG -t cboard/cboard-bootstrap:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push cboard/cboard-bootstrap:latest
          docker push cboard/cboard-bootstrap:$TAG
  

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

