  version: '3.1'

  networks:
    cboard-network:
      driver: bridge

  services:
    mongodb:
      image: mongo:4.0
      restart: on-failure
      ports:
        - "27017:27017"
      entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "repset" ]
      volumes:
        - "/data/db:/data/db"
      networks:
        - cboard-network

    cboard-api:
      image: cboard/cboard-api
      restart: on-failure
      ports:
        - "5000:80"
      environment:
        - URL
        - PORT=80
        - MONGO_URL=mongodb://mongodb/cboard-api
        - NODE_ENV=production
        - SENDGRID_API_KEY
        - AZURE_STORAGE_CONNECTION_STRING
        - JWT_SECRET
        - GOOGLE_APP_ID
        - GOOGLE_APP_SECRET
        - GOOGLE_CALLBACK_URL
        - FACEBOOK_APP_ID
        - FACEBOOK_APP_SECRET
        - FACEBOOK_CALLBACK_URL
        - APPLICATIONINSIGHTS_CONNECTION_STRING
        - IP_INFO_TOKEN
        - PAYPAL_API_CLIENT_ID
        - PAYPAL_API_CLIENT_SECRET
        - APPLE_APP_CLIENT_ID
        - APPLE_TEAM_ID
        - APPLE_KEY_ID
        - APPLE_CALLBACK_URL
        - CBOARD_APP_URL
        - SUBDOMAINS
        - AZURE_OPENAI_API_KEY
        - APP_STORE_CONNECT_API_KEY_ID
        - APP_STORE_CONNECT_API_ISSUER_ID
        - GOOGLE_FIREBASE_WEB_CLIENT_ID
        - GOOGLE_FIREBASE_SIGN_IN_APP_ID
      networks:
        - cboard-network
      depends_on:
        - mongodb
    
    cboard:
      image: cboard/cboard
      restart: on-failure
      ports:
        - "5001:80"
      networks:
        - cboard-network
      volumes:
        - "/cboard/auth:/auth"
      depends_on:
        - cboard-api
    
    cboard-wiki:
      image: cboard/cboard-wiki
      restart: on-failure
      ports:
        - "5002:80"
      environment:
        - PORT=80
      networks:
        - cboard-network

    cboard-nginx:
      image: cboard/cboard-nginx
      container_name: cboard-nginx
      restart: on-failure
      ports:
        - "80:80"
      networks:
        - cboard-network
      depends_on:
        - cboard-api
        - cboard
        - cboard-wiki
