  version: '3.1'

  networks:
    cboard-network:
      driver: bridge

  services:
    mongodb:
      image: mongo:4.0
      restart: on-failure
      ports:
        - "27017:27017"
      entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "repset" ]
      volumes:
        - "/data/db:/data/db"
      networks:
        - cboard-network

    cboard-api:
      image: cboard/cboard-api
      restart: on-failure
      ports:
        - "5000:80"
      environment:
        - URL
        - PORT=80
        - NODE_ENV=production
        - SENDGRID_API_KEY
        - AZURE_STORAGE_CONNECTION_STRING
        - JWT_SECRET
        - GOOGLE_APP_ID
        - GOOGLE_APP_SECRET
        - GOOGLE_CALLBACK_URL
        - FACEBOOK_APP_ID
        - FACEBOOK_APP_SECRET
        - FACEBOOK_CALLBACK_URL
        - APPLICATIONINSIGHTS_CONNECTION_STRING
        - IP_INFO_TOKEN
        - PAYPAL_API_CLIENT_ID
        - PAYPAL_API_CLIENT_SECRET
        - APPLE_APP_CLIENT_ID
        - APPLE_TEAM_ID
        - APPLE_KEY_ID
        - APPLE_CALLBACK_URL
        - CBOARD_APP_URL
        - SUBDOMAINS
        - AZURE_OPENAI_API_KEY
        - APP_STORE_CONNECT_API_KEY_ID
        - APP_STORE_CONNECT_API_ISSUER_ID
        - GOOGLE_FIREBASE_WEB_CLIENT_ID
        - GOOGLE_FIREBASE_SIGN_IN_APP_ID
        - INTERNAL_API_KEY
        - CBUILDER_APP_URL
      networks:
        - cboard-network
      depends_on:
        - mongodb
    
    cboard:
      image: cboard/cboard
      restart: on-failure
      ports:
        - "5001:80"
      networks:
        - cboard-network
      volumes:
        - "/cboard/auth:/auth"
      depends_on:
        - cboard-api
    
    cboard-wiki:
      image: cboard/cboard-wiki
      restart: on-failure
      ports:
        - "5002:80"
      environment:
        - PORT=80
      networks:
        - cboard-network

    cboard-cbuilder:
      image: cboard/cboard-ai-builder
      restart: on-failure
      ports:
        - "5003:80"
      environment:
        - PORT=80
        - MONGO_URL=mongodb://mongodb/cboard-ai-builder
        - NEXTAUTH_SECRET
        - NEXTAUTH_URL
        - PICTO_SERVER_ID
        - PICTO_CHANNEL_ID
        - PICTO_SALAI_TOKEN
        - NODE_TLS_REJECT_UNAUTHORIZED=0
        - CBOARD_API_URL
        - NEXT_SHARP_PATH
        - GOOGLE_APP_ID
        - GOOGLE_APP_SECRET
        - APPLE_APP_CLIENT_ID
        - APPLE_KEY_ID
        - FACEBOOK_APP_ID
        - FACEBOOK_APP_SECRET
        - AZURE_OPENAI_API_KEY
        - OPENAI_BASE_PATH
        - CONTENT_SAFETY_ENDPOINT
        - CONTENT_SAFETY_KEY
        - MYMIDJOURNEY_TOKEN
        - LEONARDO_TOKEN
        - INTERNAL_API_KEY
        - CBOARD_APP_URL_
        - LANGUAGE_KEY
        - TEXT_TRANSLATOR_API_KEY
        - GA4_TRACKING_ID
      networks:
        - cboard-network
      depends_on:
        - mongodb
        - cboard-api

    fluid-mind:
      image: cboard/fluid-mind
      restart: on-failure
      ports:
        - "5004:80"
      environment:
        - PORT=80
        - AZURE_FLOW_KEY
        - AZURE_FLOW_DEPLOYMENT
        - AZURE_FLOW_ENDPOINT
        - AZURE_TALK_KEY
        - AZURE_TALK_DEPLOYMENT
        - AZURE_TALK_ENDPOINT
        - MONGO_URL_FM=mongodb://mongodb/Fluid-Mind
        - JWT_SECRET
        - EMAIL_SERVER_USER
        - EMAIL_SERVER_PASSWORD
        - EMAIL_SERVER_HOST
        - EMAIL_SERVER_PORT
        - EMAIL_FROM
        - NEXTAUTH_SECRET
        - NEXTAUTH_URL_FM
        - GA4_TRACKING_ID_FM
      networks:
        - cboard-network
      depends_on:
        - mongodb

    cboard-nginx:
      image: cboard/cboard-nginx
      container_name: cboard-nginx
      restart: on-failure
      ports:
        - "80:80"
      networks:
        - cboard-network
      depends_on:
        - cboard-api
        - cboard
        - cboard-wiki
