  version: '3'

  networks:
    cboard-network:
      driver: bridge

  services:
    mongodb:
      image: mongo
      restart: on-failure
      ports:
        - "27017:27017"
      volumes:
        - "/data/db:/data/db"
      networks:
        - cboard-network

    cboard-api:
      image: cboard/cboard-api
      restart: on-failure
      ports:
        - "5000:80"
      environment:
        - PORT=80
        - MONGO_URL=mongodb://mongodb/cboard-api
        - NODE_ENV=production
        - SENDGRID_API_KEY
        - JWT_SECRET  
    
      networks:
        - cboard-network
      depends_on:
        - mongodb
    
    cboard:
      image: cboard/cboard
      restart: on-failure
      ports:
        - "5001:80"
      networks:
        - cboard-network
      depends_on:
        - cboard-api
    
    letsencrypt:
      image: cboard/letsencrypt
      container_name: letsencrypt
      cap_add:
        - NET_ADMIN
      links:
        - cboard
      environment:
        - URL
        - SUBDOMAINS
        - VALIDATION
        - STAGING
        - TZ
        - EMAIL
        - ONLY_SUBDOMAINS
      ports:
        - "443:443"
        - "80:80"
      networks:
        - cboard-network

